/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIparts;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import databaseConnection.DBConnection;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * @author pc
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public FastCash() {
        initComponents();
    }

    int MyAccNum;

    public FastCash(int AccNum) {
        initComponents();
        MyAccNum = AccNum;
        getBalance();


    }

    int OldBalance;

    private void getBalance() {
        try {
            String query = "SELECT * FROM accounttable WHERE AccNumber ='" + MyAccNum + "'";
            PreparedStatement pst = DBConnection.getConnection().prepareStatement(query);
            // pst.setInt(1, Integer.valueOf(AccountNumberField.getText()));
            //  pst.setInt(2, Integer.parseInt(PINfield.getText()));

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                OldBalance = rs.getInt(9);
                BalanceFastCash.setText("" + OldBalance);
            } else {
                //    JOptionPane.showMessageDialog(this, "Wrong account number or PIN", "", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, "", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        twothousandrsdbutton = new javax.swing.JButton();
        BalanceFastCash = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        onethousandrsdbutton = new javax.swing.JButton();
        fivehundredrsdbutton = new javax.swing.JButton();
        fivethousandrsdbutton = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        twothousandfivehundredrsdbutton = new javax.swing.JButton();
        tenthousandrsdbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton12.setText("Withdraw");

        jButton13.setText("Withdraw");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FastCash");

        twothousandrsdbutton.setText("2000 RSD");
        twothousandrsdbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twothousandrsdbuttonMouseClicked(evt);
            }
        });

        BalanceFastCash.setText("Balance:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreenResources/croplogo.PNG"))); // NOI18N

        onethousandrsdbutton.setText("1000 RSD");
        onethousandrsdbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onethousandrsdbuttonMouseClicked(evt);
            }
        });

        fivehundredrsdbutton.setText("500 RSD");
        fivehundredrsdbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fivehundredrsdbuttonMouseClicked(evt);
            }
        });
        fivehundredrsdbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivehundredrsdbuttonActionPerformed(evt);
            }
        });

        fivethousandrsdbutton.setText("5000 RSD");
        fivethousandrsdbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fivethousandrsdbuttonMouseClicked(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        twothousandfivehundredrsdbutton.setText("2500 RSD");
        twothousandfivehundredrsdbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twothousandfivehundredrsdbuttonMouseClicked(evt);
            }
        });

        tenthousandrsdbutton.setText("10000 RSD");
        tenthousandrsdbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenthousandrsdbuttonMouseClicked(evt);
            }
        });

        jLabel3.setText("Your balance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(twothousandrsdbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fivehundredrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(onethousandrsdbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(twothousandfivehundredrsdbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tenthousandrsdbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(94, 94, 94)
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(BalanceFastCash, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fivethousandrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(fivehundredrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(onethousandrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(twothousandrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(fivethousandrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(tenthousandrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(twothousandfivehundredrsdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BalanceFastCash)
                                        .addComponent(jLabel3))
                                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fivehundredrsdbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fivehundredrsdbuttonMouseClicked
        // TODO add your handling code here:
        if (OldBalance < 500) {
            JOptionPane.showMessageDialog(this, "Not enough money to withdraw", "", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String query = "UPDATE accounttable SET Balance = ? WHERE AccNumber = ?";
                PreparedStatement pst = DBConnection.getConnection().prepareStatement(query);
                pst.setInt(1, OldBalance - 500);
                pst.setInt(2, MyAccNum);
                if (pst.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Acount balance updated", "", JOptionPane.INFORMATION_MESSAGE);
                    new MainMenu().setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Missing information", "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, e, "", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_fivehundredrsdbuttonMouseClicked

    private void onethousandrsdbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onethousandrsdbuttonMouseClicked
        // TODO add your handling code here:
        if (OldBalance < 1000) {
            JOptionPane.showMessageDialog(this, "Not enough money to withdraw", "", JOptionPane.WARNING_MESSAGE);

        } else {


            try {
                String query = "UPDATE accounttable SET Balance = ? WHERE AccNumber = ?";
                PreparedStatement pst = DBConnection.getConnection().prepareStatement(query);
                pst.setInt(1, OldBalance - 1000);
                pst.setInt(2, MyAccNum);
                if (pst.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Acount balance updated", "", JOptionPane.INFORMATION_MESSAGE);
                    new MainMenu().setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Missing information", "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, e, "", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_onethousandrsdbuttonMouseClicked

    private void twothousandrsdbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twothousandrsdbuttonMouseClicked
        // TODO add your handling code here:
        if (OldBalance < 2000) {
            JOptionPane.showMessageDialog(this, "Not enough money to withdraw", "", JOptionPane.WARNING_MESSAGE);

        } else {


            try {
                String query = "UPDATE accounttable SET Balance = ? WHERE AccNumber = ?";
                PreparedStatement pst = DBConnection.getConnection().prepareStatement(query);
                pst.setInt(1, OldBalance - 2000);
                pst.setInt(2, MyAccNum);
                if (pst.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Acount balance updated", "", JOptionPane.INFORMATION_MESSAGE);
                    new MainMenu().setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Missing information", "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, e, "", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_twothousandrsdbuttonMouseClicked

    private void twothousandfivehundredrsdbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twothousandfivehundredrsdbuttonMouseClicked
        // TODO add your handling code here:
        if (OldBalance < 2500) {
            JOptionPane.showMessageDialog(this, "Not enough money to withdraw", "", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String query = "UPDATE accounttable SET Balance = ? WHERE AccNumber = ?";
                PreparedStatement pst = DBConnection.getConnection().prepareStatement(query);
                pst.setInt(1, OldBalance - 2500);
                pst.setInt(2, MyAccNum);
                if (pst.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Acount balance updated", "", JOptionPane.INFORMATION_MESSAGE);
                    new MainMenu().setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Missing information", "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, e, "", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_twothousandfivehundredrsdbuttonMouseClicked

    private void fivethousandrsdbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fivethousandrsdbuttonMouseClicked
        // TODO add your handling code here:
        if (OldBalance < 5000) {
            JOptionPane.showMessageDialog(this, "Not enough money to withdraw", "", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String query = "UPDATE accounttable SET Balance = ? WHERE AccNumber = ?";
                PreparedStatement pst = DBConnection.getConnection().prepareStatement(query);
                pst.setInt(1, OldBalance - 5000);
                pst.setInt(2, MyAccNum);
                if (pst.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Acount balance updated", "", JOptionPane.INFORMATION_MESSAGE);
                    new MainMenu().setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Missing information", "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, e, "", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_fivethousandrsdbuttonMouseClicked

    private void tenthousandrsdbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenthousandrsdbuttonMouseClicked
        // TODO add your handling code here:
        if (OldBalance < 10000) {
            JOptionPane.showMessageDialog(this, "Not enough money to withdraw", "", JOptionPane.WARNING_MESSAGE);

        } else {

            try {
                String query = "UPDATE accounttable SET Balance = ? WHERE AccNumber = ?";
                PreparedStatement pst = DBConnection.getConnection().prepareStatement(query);
                pst.setInt(1, OldBalance - 10000);
                pst.setInt(2, MyAccNum);
                if (pst.executeUpdate() == 1) {
                    JOptionPane.showMessageDialog(this, "Acount balance updated", "", JOptionPane.INFORMATION_MESSAGE);
                    new MainMenu().setVisible(true);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Missing information", "", JOptionPane.WARNING_MESSAGE);
                }
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                JOptionPane.showMessageDialog(this, e, "", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_tenthousandrsdbuttonMouseClicked

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void fivehundredrsdbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivehundredrsdbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fivehundredrsdbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatMaterialLighterIJTheme());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceFastCash;
    private javax.swing.JButton fivehundredrsdbutton;
    private javax.swing.JButton fivethousandrsdbutton;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton onethousandrsdbutton;
    private javax.swing.JButton tenthousandrsdbutton;
    private javax.swing.JButton twothousandfivehundredrsdbutton;
    private javax.swing.JButton twothousandrsdbutton;
    // End of variables declaration//GEN-END:variables
}
